// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpzDmMHrKWUh7wl7jB1rDGh6bnDeDVzsQ',
    appId: '1:890972242336:web:53256189a7646f6ff764c5',
    messagingSenderId: '890972242336',
    projectId: 'pushnotitutorial-520e2',
    authDomain: 'pushnotitutorial-520e2.firebaseapp.com',
    storageBucket: 'pushnotitutorial-520e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNZzRnD8WGY8nGr91h1uR8v3EZcaquf6I',
    appId: '1:890972242336:android:c154d53d8a983ecbf764c5',
    messagingSenderId: '890972242336',
    projectId: 'pushnotitutorial-520e2',
    storageBucket: 'pushnotitutorial-520e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATbvBWwOotR4QSpu7--2DcfflWDOdvzd0',
    appId: '1:890972242336:ios:58332d6205878199f764c5',
    messagingSenderId: '890972242336',
    projectId: 'pushnotitutorial-520e2',
    storageBucket: 'pushnotitutorial-520e2.appspot.com',
    iosBundleId: 'com.example.sampleshopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATbvBWwOotR4QSpu7--2DcfflWDOdvzd0',
    appId: '1:890972242336:ios:58332d6205878199f764c5',
    messagingSenderId: '890972242336',
    projectId: 'pushnotitutorial-520e2',
    storageBucket: 'pushnotitutorial-520e2.appspot.com',
    iosBundleId: 'com.example.sampleshopping',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpzDmMHrKWUh7wl7jB1rDGh6bnDeDVzsQ',
    appId: '1:890972242336:web:1ecbd498ee5934d3f764c5',
    messagingSenderId: '890972242336',
    projectId: 'pushnotitutorial-520e2',
    authDomain: 'pushnotitutorial-520e2.firebaseapp.com',
    storageBucket: 'pushnotitutorial-520e2.appspot.com',
  );
}
